In [1]:
import os, sys
import time 
import numpy as np
from sim.RunSim import runSim
# import sim.importModules as mods
# from sim.InitializeScenario import InitializeScenario
# from generalUtilities.pchipInterp_SciPy import pchip

if sys.version_info[2] > 2:
    from scipy.interpolate import pchip_interpolate
    
    # SciPy interpolation Routine:"
    def InterpTraj_SciPy(trajectory, time):
        column = trajectory.shape[1]
        trajTime = pchip_interpolate(trajectory[:,6], trajectory[:, 0:column], time)
        print("using SciPy pchip_interpolate. Resultant matrix size: {}".format(trajTime.shape))
        return trajTime

    # My interpolation Routine:
    def InterpTraj_Brent(trajectory, time):
        columns = trajectory.shape[1]
        trajTime = pchip(trajectory[:, 6], trajectory[:,0:columns], time).transpose()
        print("using in house pchip routine. Resultant matrix size: {}".format(trajTime.shape))
        return trajTime

else:
    print("using version: {}.{}.{} of python, scipy is not available.".format(
        sys.version_info[0],sys.version_info[1],sys.version_info[2]))
    
    def InterpTraj(trajectory, time):
        column = trajectory.shape[1]
        trajTime = np.zeros((time.shape[0], trajectory.shape[1]))
        for column in range(trajectory.shape[1]-1):
            trajTime[:,column] = pchip(trajectory[:, 6], trajectory[:,column], time).transpose()
        print("using in house pchip routine. Resultant matrix size: {}".format(trajTime.shape))
        return trajTime


using version: 2.7.2 of python, scipy is not available.


In [2]:
start = time.clock()
kvStatesFinal = runSim()
elapsedTime = time.clock() - start

# Threat Objects     = 6
# Threat Clouds      = 1
Threat Divergence    = 16.6666666667 m/s
EV Radius            = 10548.6073848 m
Closing Velocity     = 8844.74645866 m/s
Closing Angle        = 88.3063080721 deg
rvID                 = 2
Processing time step t = 1.0
current elapsed time = 2.99999999998e-06s
Processing time step t = 2.0
current elapsed time = 0.002234s
Processing time step t = 3.0
current elapsed time = 0.004248s
Processing time step t = 4.0
current elapsed time = 0.006179s
Processing time step t = 5.0
current elapsed time = 0.008154s
Processing time step t = 6.0
current elapsed time = 0.010172s
Processing time step t = 7.0
current elapsed time = 0.012115s
Processing time step t = 8.0
current elapsed time = 0.014045s
Processing time step t = 9.0
current elapsed time = 0.015976s
Processing time step t = 10.0
current elapsed time = 0.017897s
Processing time step t = 11.0
current elapsed time = 0.019841s
Processing time step t = 12.0
current elapsed time = 0.021824s
Process

Processing time step t = 210.0
current elapsed time = 0.417503s
Processing time step t = 211.0
current elapsed time = 0.419888s
Processing time step t = 212.0
current elapsed time = 0.422025s
clusterIds: [0 1 2]
nKV: 0, iKV: 0, nKVs: 6, nClsts: 3
nKV: 1, iKV: 1, nKVs: 6, nClsts: 3
nKV: 2, iKV: 2, nKVs: 6, nClsts: 3
available threats: [0 1 2 3 4 5], 
assigned final threats: [0 0 0 0 0 0]
nKVs: 6 
assignedThreats: [-1. -1. -1. -1. -1. -1.] 
validAssignments: []
Processing time step t = 213.0
current elapsed time = 0.709452s
available threats: [0 1 2 3 4 5], 
assigned final threats: [0 0 0 0 0 0]
nKVs: 6 
assignedThreats: [-1. -1. -1. -1. -1. -1.] 
validAssignments: []
Processing time step t = 214.0
current elapsed time = 0.969313s
available threats: [0 1 2 3 4 5], 
assigned final threats: [0 0 0 0 0 0]
nKVs: 6 
assignedThreats: [-1. -1. -1. -1. -1. -1.] 
validAssignments: []
Processing time step t = 215.0
current elapsed time = 1.221235s
available threats: [0 1 2 3 4 5], 
assigned final 


option 4 bias: [ 6.25271108  0.04074948]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 2
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.25282316  0.04060283]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 3
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.25270564  0.0406374 ]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 4
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.25270651  0.04062026]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.25270841  0.04062027]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [3 1]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [3 1]
original lethality es


option 4 bias: [ 6.25529157  0.03714467]
object pairs: 
[[2 2]
 [0 4]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.25529338  0.03714467]
object pairs: 
[[2 2]
 [0 4]
 [3 5]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [3 5]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [3 5]
original lethality estimate: 0.0313425786061
 updated lethality estimate: 0.0918787719555
available threats: [0 1 2 3 4 5], 
assigned final threats: [0 0 0 0 0 0]
nKVs: 6 
assignedThreats: [-1. -1. -1. -1. -1. -1.] 
validAssignments: []
Processing time step t = 248.0
current elapsed time = 30.585357s

processing data for KV 0
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.25560829  0.03651101]
object pairs: 
[[2 2]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 1
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6

available threats: [0 1 2 3 4 5], 
assigned final threats: [0 0 0 0 0 0]
nKVs: 6 
assignedThreats: [-1. -1. -1. -1. -1. -1.] 
validAssignments: []
Processing time step t = 253.0
current elapsed time = 47.433039s

processing data for KV 0
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.25856858  0.03266292]
object pairs: 
[[2 4]
 [0 0]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 1
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.25873462  0.03286581]
object pairs: 
[[2 4]
 [0 0]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 2
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.2588888   0.03266479]
object pairs: 
[[2 4]
 [0 0]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 3
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.2587284   0.03272188]
object pairs: 
[[2 4]
 [0 0]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data


option 4 bias: [ 6.26094665  0.02980768]
object pairs: 
[[2 2]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 2
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26111984  0.02958201]
object pairs: 
[[2 2]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 3
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26094003  0.02964933]
object pairs: 
[[2 2]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 4
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26094077  0.02963689]
object pairs: 
[[2 2]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26094233  0.02963689]
object pairs: 
[[2 2]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [3 5]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [3 5]
original lethality es


option 4 bias: [ 6.26367913  0.02587805]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26368055  0.02587806]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [3 1]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [3 1]
original lethality estimate: 0.193798574369
 updated lethality estimate: 0.195713832797
available threats: [0 1 2 3 4 5], 
assigned final threats: [0 0 0 0 0 0]
nKVs: 6 
assignedThreats: [-1. -1. -1. -1. -1. -1.] 
validAssignments: []
Processing time step t = 264.0
current elapsed time = 82.345416s

processing data for KV 0
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26407562  0.02487925]
object pairs: 
[[2 5]
 [0 4]
 [3 2]] 
rfObjects: 3 
irObjects: 4

processing data for KV 1
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.2

available threats: [0 1 2 3 4 5], 
assigned final threats: [0 0 0 0 0 0]
nKVs: 6 
assignedThreats: [-1. -1. -1. -1. -1. -1.] 
validAssignments: []
Processing time step t = 269.0
current elapsed time = 98.606699s

processing data for KV 0
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26668093  0.02170772]
object pairs: 
[[2 1]
 [0 4]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 1
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26691369  0.02197977]
object pairs: 
[[2 1]
 [0 4]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 2
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26712876  0.02169963]
object pairs: 
[[2 1]
 [0 4]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 3
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26690612  0.02178957]
object pairs: 
[[2 1]
 [0 4]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data


option 4 bias: [ 6.26916034  0.01825183]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 2
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26939447  0.0179468 ]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 3
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26915231  0.01804707]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 4
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26915284  0.01803936]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.26915391  0.01803936]
object pairs: 
[[2 2]
 [0 4]
 [3 1]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [2 2]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [2 2]
original lethality es

sim/KinematicReach.py:63: RuntimeWarning: invalid value encountered in sqrt
  tBurn = dT - np.sqrt( dT**2 - (2/aMax) * np.linalg.norm(pT - p0 - v0*dT) )


available threats: [0 1 2 3 4 5], 
assigned final threats: [0 4 0 0 1 0]
nKVs: 6 
assignedThreats: [-1.  4. -1. -1.  1. -1.] 
validAssignments: [4 1]
Processing time step t = 279.0
current elapsed time = 131.619887s

processing data for KV 0
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27172591  0.0149936 ]
object pairs: 
[[2 1]
 [0 2]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 1
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27203106  0.01528659]
object pairs: 
[[2 1]
 [0 2]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 2
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27225364  0.01497927]
object pairs: 
[[2 1]
 [0 2]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 3
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27199224  0.01508974]
object pairs: 
[[2 1]
 [0 2]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing 


option 4 bias: [ 6.27512556  0.01133864]
object pairs: 
[[2 4]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 2
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27521691  0.0111159 ]
object pairs: 
[[2 4]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 3
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27506426  0.01114375]
object pairs: 
[[2 4]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 4
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27499442  0.01119664]
object pairs: 
[[2 4]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.2749876   0.01119381]
object pairs: 
[[2 4]
 [0 0]
 [3 5]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [3 5]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [3 5]
original lethality es


option 4 bias: [ 6.27783123  0.00767811]
object pairs: 
[[2 4]
 [0 0]
 [3 3]] 
rfObjects: 3 
irObjects: 4

processing data for KV 4
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27766583  0.00779452]
object pairs: 
[[2 4]
 [0 0]
 [3 3]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [ 6.27768569  0.00774554]
object pairs: 
[[2 4]
 [0 0]
 [3 3]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [2 4]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [2 4]

EXCEPTION OCCURRED 7: 
irIndex: 4, rfIndex: 2
available ifIndices: [5 2 1 3]

original lethality estimate: 0.613824309996
 updated lethality estimate: 0.617809413497
available threats: [0 1 2 3 4 5], 
assigned final threats: [5 4 3 2 1 0]
nKVs: 6 
assignedThreats: [ 5.  4.  3.  2.  1. -1.] 
validAssignments: [5 4 3 2 1]
Processing time step t = 290.0
current elapsed time = 169.249224s

processing data f


option 4 bias: [  6.27956951e+00   4.25494152e-03]
object pairs: 
[[2 2]
 [0 3]
 [3 1]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [-0.00321205  0.00411673]
object pairs: 
[[2 2]
 [0 3]
 [3 1]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [2 2]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [2 2]
original lethality estimate: 0.764352258252
 updated lethality estimate: 0.760427553736
available threats: [0 1 2 3 4 5], 
assigned final threats: [5 4 3 2 1 0]
nKVs: 6 
assignedThreats: [ 5.  4.  3.  2.  1. -1.] 
validAssignments: [5 4 3 2 1]
Processing time step t = 295.0
current elapsed time = 185.963588s

processing data for KV 0
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [  6.28008901e+00   3.49783853e-03]
object pairs: 
[[2 0]
 [0 2]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 1
shape of arrays we want to remove bias from: (3, 2)


option 4 bias: [  6.28189650e+00  -5.35749064e-04]
object pairs: 
[[2 0]
 [0 2]
 [3 5]] 
rfObjects: 3 
irObjects: 4

processing data for KV 5
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [  6.28184992e+00  -8.01045653e-04]
object pairs: 
[[2 0]
 [0 2]
 [3 5]] 
rfObjects: 3 
irObjects: 4
winners from determine winner: [2 0]
tomCorrData shape: (6, 3, 2)
winner from tomCorrelation: [2 0]

EXCEPTION OCCURRED 9: 
irIndex: 0, rfIndex: 2
available ifIndices: [5 2 1 3]

original lethality estimate: 0.343069358916
 updated lethality estimate: 0.356012656474
available threats: [0 1 2 3 4 5], 
assigned final threats: [5 4 3 2 1 0]
nKVs: 6 
assignedThreats: [ 5.  4.  3.  2.  1. -1.] 
validAssignments: [5 4 3 2 1]
Processing time step t = 300.0
current elapsed time = 202.444974s

processing data for KV 0
shape of arrays we want to remove bias from: (3, 2), (4, 2)

option 4 bias: [  6.28157851e+00  -1.82257193e-03]
object pairs: 
[[2 4]
 [0 2]
 [3 1]] 
rfObjects: 3 
i

IndexError: invalid index

In [ ]:
print("elapsedTime: {}s".format(elapsedTime))
print("kvStates shape: {}".format(kvStatesFinal.shape))
print("kvStates: \n{}".format(kvStatesFinal))

# Code Breakdown

In [ ]:
def ReCenter(distPts, distCtr, distMax):
    # calculate distance between each point and desired center
    difference = np.subtract(distPts, distCtr)
    distance = mods.vecNorm(difference, axis=1)
    # get list of measurements that are within distance, dist, from center
    ids = np.where(distance < distMax)[0]
    if ids.size > 0:
        distRed = distPts[ ids ]
        # compute new center based on arithmetic mean of reduced values
        newCtr = np.mean(distRed, axis=0)
        # find the point closest to the new center from the reduced list
        newDist = mods.vecNorm( np.subtract(distRed, newCtr), axis=1 )
        nearestId = np.argmin(newDist)
    else:
        print("Empty list in recenter??")
        distRed = np.empty(0)
        nearestId = -1

    return newCtr, nearestId

def FarPoint(distPts, distCtr, distMax=1e17):
    # calculate distance between each point and desired center
    print("distPts: {}, distCtr: {}".format(distPts.shape, distCtr.shape))
    difference = np.subtract(distPts, distCtr)
    distance = mods.vecNorm(difference, axis=1)
    # get list of measurements that are within distance, distMax, from center
    ids = np.where(distance < distMax)[0]
    if ids.size > 0:
        distRed = distPts[ids]
        newDist = distance[ids]
        # find the point furthest from distCtr in the reduced list
        farthestId = np.argmax(newDist)
        newCtr = distRed[ farthestId ]
        farDist = newDist[ farthestId ]
    else:
        print("No points within distance {} of point {}".format(distMax, distCtr))
        farthestId = np.argmax(distance)
        newCtr = distPts[ farthestId ]
        farDist = distance[ farthestId ]

    return newCtr, farthestId, farDist

def kMeans(dataSet, desiredClusters):
    mu = np.zeros((desiredClusters, dataSet.shape[1]))
    isSatisfied = False

    # find the closest mean for each data point
    while not isSatisfied:
        labels = np.random.randint(0, desiredClusters, size=(dataSet.shape[0], 1))
        print("initial labels: {}".format(labels))
        randIds = np.random.permutation( np.arange(dataSet.shape[0]) )
        subIndices = np.array_split(randIds, desiredClusters)
        counts = np.zeros(desiredClusters)
        newDataSet = np.hstack((dataSet, labels))
        # break up the points into roughly equal sized chunks
        iteration = 0
        for ids in subIndices:
            subSet = dataSet[ids]
            mu[iteration] = np.mean(subSet, axis=0)
            iteration += 1
        # find the minimum distance between each point and the group mean
        for vector in newDataSet:
            vectorId = np.where(newDataSet == vector)[0][0]
            difference = np.subtract(vector[0:3], mu)
            distance = mods.vecNorm(difference, axis=1)
            # figure out which cluster wins and add the vector to that list
            clusterId = np.argmin(distance)
            vector[-1] = clusterId
            labels[vectorId] = clusterId

        # find out how many points are in each cluster, if its not 'equally' 
        # distributed run this again
        for clusterId in range(desiredClusters):
            counts[clusterId] = np.where(newDataSet[-1] == clusterId)[0].size

        if not np.allclose(counts, dataSet.shape[0]/desiredClusters, atol = 1.0):
            isSatisfied = False
        else:
            isSatisfied = True
            break

    print("final labels: {}".format(labels))
    # ouput results and labels
    return mu, labels


In [ ]:
def FindPOCA(kaState, trgtState, interpRoutine=None):
    # Propagate states at couarse resolution (5s)
    kaTraj, trgtTraj = mods.PropagateStatesToDivergence(kaState, trgtState, 2.5)

    # interpolate states around the coarse resolution POCA - coarse resolution
    # POCA is the 2nd to las trajectory point of the target
    if interpRoutine != None:
        if interpRoutine == 'SciPy':
            r = kaTraj.shape[0]
            tToInterp = np.arange(kaTraj[r-4, 6], kaTraj[r-1, 6], 0.01)
            interpKA = InterpTraj_SciPy(kaTraj, tToInterp)
            interpTrgt = InterpTraj_SciPy(trgtTraj, tToInterp)
        else:
            r = kaTraj.shape[0]
            tToInterp = np.arange(kaTraj[r-4, 6], kaTraj[r-1, 6], 0.01)
            interpKA = InterpTraj_Brent(kaTraj, tToInterp)
            interpTrgt = InterpTraj_Brent(trgtTraj, tToInterp)
    else:
        r = kaTraj.shape[0]
        tToInterp = np.arange(kaTraj[r-4, 6], kaTraj[r-1, 6], 0.01)
        interpKA = mods.InterpTraj(kaTraj, tToInterp)
        interpTrgt = mods.InterpTraj(trgtTraj, tToInterp)

    # find the fine resolution POCA (0.01s)
    rKA = interpKA[:, 0:3]
    rTrgt = interpTrgt[:, 0:3]
    rDiff = rKA - rTrgt
    rMag = mods.vecNorm(rDiff, axis=1)
    
    # finding the maximum result, arbitrarily using the first hit in case there are multiple
    dRPOCA = rMag.min()
    ind = rMag.argmin()

    # return the values
    tPOCA = interpTrgt[ind, 6]
    rPOCA = interpTrgt[ind, 0:3]

    return tPOCA, rPOCA, dRPOCA


In [ ]:
import sim.importModules as mods
from sim.InitializeScenario import InitializeScenario

SAPs = mods.SAPs
rCVFinal = np.array([-7, 0, 0]) * 1e6
cvSpeed = mods.UniformRandRange(SAPs.CV_SPEED_MIN, SAPs.CV_SPEED_MAX)
vCVFinal = np.array([0, 1, 0]) * cvSpeed
rPdmFinal = rCVFinal

# generate the final states of the CV and threat PDM
tStart = SAPs.MDL_T_START
tFinal = tStart + SAPs.MDL_T_DURATION

In [ ]:
inBounds = False
while not inBounds:
    v = np.array([0, np.random.randn(), np.random.randn()])
    v = v / np.linalg.norm(v)
    theta = mods.AngleBetweenVecs(vCVFinal, v)
    if theta > SAPs.CV_CLOSE_ANGLE_MIN and theta <= SAPs.CV_CLOSE_ANGLE_MAX:
        inBounds = True

In [ ]:
# generate the final states of the CV and threat PDM
tStart = SAPs.MDL_T_START
tFinal = tStart + SAPs.MDL_T_DURATION
rCVFinal = np.array([-7, 0, 0]) * 1e6       # final CV position [ECI, m]
cvSpeed = mods.UniformRandRange(SAPs.CV_SPEED_MIN, SAPs.CV_SPEED_MAX)
vCVFinal = np.array([0, 1, 0]) * cvSpeed    # final CV velocity [ECI, m]
rPdmFinal = rCVFinal                        # final Payload Deployment Module (PDM) position, [ECI, m]
inBounds = False
while not inBounds:
    v = np.array([0, np.random.randn(), np.random.rand()])
    v = v / np.linalg.norm(v)
    theta = mods.AngleBetweenVecs(vCVFinal, v)
    if theta > SAPs.CV_CLOSE_ANGLE_MIN and theta <= SAPs.CV_CLOSE_ANGLE_MAX:
        inBounds = True

thtSpeed = mods.UniformRandRange(SAPs.THT_SPEED_MIN, SAPs.THT_SPEED_MAX)
vPdmFinal = v * thtSpeed
vClose = np.linalg.norm(vPdmFinal - vCVFinal)
aClose = mods.AngleBetweenVecs(vPdmFinal, vCVFinal)

tmpState = np.append(rPdmFinal, vPdmFinal)
tmpState = np.append(tmpState, SAPs.MDL_T_DURATION)
# generate the initial threat PDM state
sPdmInitial = mods.PropagateECI(tmpState.reshape(7,1), 0.0, -SAPs.MDL_T_DURATION)

# generate the center point of each cloud. the PDM is in the center of the complex
# while other clouds surround it.
nClouds = np.random.randint(SAPs.THT_MIN_NUM_CLOUDS, SAPs.THT_MAX_NUM_CLOUDS+1)
rCloud = np.zeros((nClouds, 3))
thtRadius = mods.UniformRandRange(SAPs.THT_MIN_RADIUS, SAPs.THT_MAX_RADIUS)[0]
for iCloud in range(nClouds):
    # compute the position of the cloud w.r.t. the PDM at the final time
    delR = np.random.rand(1,3)
    delR = delR / np.linalg.norm(delR)
    delR = delR * np.absolute( np.random.randn() * thtRadius )
    rCloud[iCloud] = rPdmFinal + delR

# generate the position of each threat at time = tFinal
rDeviation = SAPs.THT_POS_DEV * np.random.rand()
nThreats = np.random.randint(SAPs.THT_MIN_NUM_OBJS, SAPs.THT_MAX_NUM_OBJS+1)
threatStates = np.zeros((nThreats, 7))
for iThreat in range(nThreats):
    # determine which cloud this threat belongs to
    iCloud = np.random.randint(0, nClouds)
    # determine it's final state
    rFinal = rCloud[iCloud] + np.random.randn(1,3) * rDeviation
    sFinal, _ = mods.GaussProblem(rFinal, sPdmInitial[0:3], SAPs.MDL_T_DURATION)
    vFinal = -sFinal[3:6]
    threatStates[iThreat, 0:3] = rFinal
    threatStates[iThreat, 3:6] = vFinal
    threatStates[iThreat, 6] = tFinal

# compute the average state
aveState = np.sum(threatStates, axis=0) / nThreats
aveState = mods.PropagateECI(aveState.reshape(7,1), 0.0, -SAPs.MDL_T_DURATION)

# now propagate everything back to time = tStart
tmpCVState = np.concatenate((rCVFinal.reshape(1,3), vCVFinal.reshape(1,3)), axis=1)
tmpCVState = np.append(tmpCVState, tFinal)
cvState = mods.PropagateECI(tmpCVState.reshape(7,1), 0.0, -SAPs.MDL_T_DURATION)

for iThreat in range(nThreats):
    threatStates[iThreat] = mods.PropagateECI(threatStates[iThreat].reshape(7,1), 0.0, -SAPs.MDL_T_DURATION)

# perform initial CV divert
tPOCA, rPOCA, _ = mods.FindPOCA(cvState, aveState)

print("results from FindPOCA: \n{} \n{}".format(tPOCA, rPOCA))

rndID = np.random.randint(threatStates.shape[0])

threatStatesTest = mods.PropagateECI(threatStates[rndID], 0, 0)

if np.allclose(threatStatesTest, threatStates[rndID]):
    print "PropagateECI for 0 time works"
else:
    print("PropagateECI for 0 time failed: {}".np.diff(threatStatesTest, threatStates[rndID]))


In [ ]:
[cvState, cvFuel, threatStates, rvID, tankID, tPOCA, rPOCA, vClose, aClose, thtRadius] = InitializeScenario()

print("cvStates: {}".format(cvState))

t = SAPs.MDL_T_START + SAPs.MDL_T_DURATION + 1.0

nThreats = threatStates.shape[0]

pLethalGround = mods.DiscriminationGround(nThreats, rvID, SAPs.RDR_KFACTOR)
pLethalOnboard = mods.DiscriminationOnboard(nThreats, rvID, SAPs.RDR_KFACTOR)

# print("pLethalGround: {}".format(pLethalGround))
# print("pLethalOnboard: {}".format(pLethalOnboard))

# tom, tomCov, tomIds = mods.MakeTOM(threatStates,rvID, t, pLethalGround, SAPs.RDR_FRAC_TRACKS_DETECTED)
tom, tomCov, tomIds = mods.MakeTOM(threatStates,rvID, t, pLethalGround, SAPs.CV_FRAC_TRACKS_DETECTED)

print("\nnThreats: {}, pLethalGround size: {}, pLethalOnboard size: {}".format(nThreats, pLethalGround.shape[0], pLethalOnboard.shape[0]))
print("tom: \n{}".format(tom))
print("size of tom: {}".format(tom.shape))
print("tomIds: {}".format(tomIds))
print("number of threats in original lise: {}".format(threatStates.shape[0]))
print("actual threat states: \n{}".format(threatStates[:,-1]))

In [ ]:
kvStates = np.ones((mods.SAPs.KV_NUM_KVS, 7))
for iKV in range(kvStates.shape[0]):
#     kvState = np.random.randn(cvState.size) * cvState
    kvStates[iKV] = mods.PropagateECI(kvStates[iKV], 0.0, mods.SAPs.MDL_T_START + mods.SAPs.MDL_TIMESTEP)

onboardThreats = mods.MakeOnboardThreats(threatStates, rvID, pLethalOnboard, mods.SAPs.CV_FRAC_TRACKS_DETECTED)

randIndx = np.random.randint(onboardThreats[2].size, size=(1))
# print("covariance directly from onboardThreats: {}".format(onboardThreats[1]))
print("number of threats from TOM: {}".format(tomIds.size))
print("number of threats onBoard : {}".format(onboardThreats[2].size))
print("number of threats in original list: {}".format(threatStates.shape[0]))
print("fraction of threats seen (SAPs #) : {}".format(SAPs.CV_FRAC_TRACKS_DETECTED))
tomCorrData , winner = mods.CorrelateTOM(tom, tomCov, tomIds, onboardThreats[0], onboardThreats[1], onboardThreats[2], SAPs.KV_NUM_KVS, rvID, kvStates)

print("tomCorrData: \n{}, \nwinner: {}".format(tomCorrData, winner))

In [ ]:
kvsDispensed = False
# dispense the KVs (when its time)
# TODO investigate multiple dispenses (e.g. 1st for furthest threat
# clusters)
# TODO give time for start shot    
if tFinal - t <= SAPs.KV_BATTERY_LIFE and not kvsDispensed:
    kvStates = mods.DispenseKVs(cvState)
    kvsDispensed = True
    tDispense = t

tPOCAt, rPOCAt, _ = mods.FindPOCA(cvState, tom[int( np.where(tom[:,8] == tomIds[2])[0] ), 0:7])
cv, _ = mods.GaussProblem(cvState[0:3], rPOCA, tPOCA - cvState[6])
kvFuel = np.ones(SAPs.KV_NUM_KVS) * SAPs.KV_MAX_DIVERT

tomIds = tomCorrData[0][:,0].astype(int)

print("original Toms: {}".format(tom[:,8].astype(int)))

print("new tom Ids: {}".format(tomIds))

condition = [np.asscalar(np.where(tom[:,8]  == idNumber)[0]) for idNumber in tomIds]

print("checking condition: {}".format(condition))

tomStates = tom[condition, 0:7]

print("new tomStates: \n{}".format(tomStates))
for iTomThrt in range(tomStates.shape[0]):
    tomStates[iTomThrt] = mods.PropagateECI(tomStates[iTomThrt, 0:7], 0.0, t - tomStates[iTomThrt, 6])


try:
    ind = int( np.where(tomIds == rvID) ) 
    rvIdTmp = int( tomIds[ind] )
except TypeError:
    rvIdTmp = 0

print("threatIds directly from tom: {}".format(tomIds))

# pRVs = pLethalGround

# DeployKVs
cvState, cvFuel, kvStates, kvFuel, clusters = mods.DeployKVsTOM(cvState, cvFuel, kvStates, kvFuel, 
        tomStates, tomIds, pLethalGround, tPOCA, rvIdTmp, 'aH5')

print("number of clusters: {}".format(len(clusters))) 

In [ ]:
krMatrix, dVMatrix = mods.KinematicReach(cvState, kvStates, kvFuel, threatStates)

pkMat = krMatrix * SAPs.WTA_AVE_KV_PK

lethality = np.tile(pLethalGround, (SAPs.KV_NUM_KVS, 1))
costMat = lethality * pkMat
costMat = (1 - costMat) * krMatrix
condition = (costMat[:,:] == 0)
costMat[condition] = 1.0
planMat = mods.munkres(costMat)
#VisualizeWTA(planMat, ~krMatrix, pLethalGround, [], [], [], [], aH6)
# final assignment determination (kv-by-kv basis)
inThreatIds = np.arange(threatStates.shape[0])
finalAssign, kvStates = mods.FinalAssignment(planMat, kvStates, kvFuel, threatStates, inThreatIds, 5.0)

print("costMat shape: {}".format(costMat.shape))
print("actual cost matrix: \n{}".format(costMat))
print("finalAssign: {}".format(finalAssign))

In [ ]:
# kvFuel = np.ones(SAPs.KV_NUM_KVS) * SAPs.KV_MAX_DIVERT

# tomIdsReal = tom[:, 8]
# tomIdsTmp = np.arange(tom.shape[0])
# try:
#     ind = int( np.where(tomIdsReal == rvID) ) 
#     rvIdTmp = int( tomIdsTmp[ind] )
# except TypeError:
#     rvIdTmp = 0
    
# threatIDs = tomIdsReal.copy()

# pRVs = tom[:, 7]
# threatStates = np.zeros
# threatStates = np.empty((tom.shape[0], 7))
# for iTomThrt in range(tom.shape[0]):
#     threatStates[iTomThrt] = PropagateECI(tom[iTomThrt, 0:7], 0.0, t - tom[iTomThrt, 6])
    
tPOCAt, rPOCAt, _ = mods.FindPOCA(cvState, tom[int( np.where(tom[:,8] == tomIds[2])[0] ), 0:7])
cv, _ = mods.GaussProblem(cvState[0:3], rPOCA, tPOCA - cvState[6])
kvFuel = np.ones(SAPs.KV_NUM_KVS) * SAPs.KV_MAX_DIVERT

threatStates = np.empty((tom.shape[0], 7))
for iTomThrt in range(tom.shape[0]):
    threatStates[iTomThrt] = mods.PropagateECI(tom[iTomThrt, 0:7], 0.0, t - tom[iTomThrt, 6])

threatStates = tom[:,0:7]

tomIdsReal = tom[:, 8]
threatIds = tom[:, 8]

print("input threatIds: {}".format(threatIds))
print("threatIds directly from tom: {}".format(tomIds))

pRVs = pLethalGround

clusterList = mods.Cluster(cvState=cvState,kvFuel=kvFuel,threatStates=threatStates, 
                   threatIds=tomIds, tPOCA=tPOCA, aH1='a')


print("pRVs: {}".format(pRVs))
# print("cluster ids: {}".format(cluster.ids))

# Now compute the number of KVs to send to each cluster based on the number of 
# threats and their lethality ranking
nClusters = len(clusterList)
pLethalNorm = pRVs / np.sum(pRVs)

print("")
weights = np.zeros(nClusters)
indx = 0
for cluster in clusterList:
    weights[indx] = np.sum( pLethalNorm[cluster.ids] )
    print("cluster {} ids: {}".format(indx, cluster.ids))
    indx += 1

nAssigned = np.round(weights * SAPs.KV_NUM_KVS)
nAssignedRAW = weights * SAPs.KV_NUM_KVS

print("pLethalNorm: {}, \npRVs: {}, \nweights: {}".format(pLethalNorm, pRVs, weights))
print("nClusters: {}, \nnAssigned: {}".format(nClusters, nAssigned))
# If there are any left over, assign them to the cluster with the largest number of threats.
# If there are too many assigned, get rid of one with the most assignments.
nLeftOver = SAPs.KV_NUM_KVS - np.sum(nAssigned)

while nLeftOver != 0:
    if nLeftOver < 0 and nAssigned.size > 0:
        adjIndex = np.unravel_index(nAssigned.argmax(), dims=nAssigned.shape)
    elif nLeftOver > 0 and nAssigned.size > 0:
        adjIndex = np.unravel_index(weights.argmax(), dims=nAssigned.shape)
    # adjust nAssigned accordingly    
    nAssigned[adjIndex] = nAssigned[adjIndex] + 1
    nLeftOver -= 1

print("number of KVs: {}".format(SAPs.KV_NUM_KVS))
print("nAssigned = {}".format(nAssigned))
print("nAssignedRAW = {}".format(nAssignedRAW))
print("nLeftOver = {}".format(nLeftOver))

In [ ]:
tPOCAt, rPOCAt, _ = mods.FindPOCA(cvState, tom[int( np.where(tom[:,8] == tomIds[2])[0] ), 0:7])
cv, _ = mods.GaussProblem(cvState[0:3], rPOCA, tPOCA - cvState[6])
kvFuel = np.ones(SAPs.KV_NUM_KVS) * SAPs.KV_MAX_DIVERT

dV = np.linalg.norm( cv[3:6] - cvState[0:3] )
dC = np.random.rand(3)
d = np.random.rand(7,3)
dVAfterDivert = kvFuel[0] - dV - SAPs.KV_FUEL_RESERVE

killRadius = dVAfterDivert*SAPs.CV_FINAL_ASSGN_TGO

dC, _ = ReCenter(d, dC, killRadius)
ldC = np.zeros(3)
print("dC shape:  {}".format(dC.shape))
print("ldC shape: {}".format(ldC.shape))
print("norm of the difference: {}".format(np.linalg.norm( np.subtract(dC, ldC) )))
print("d.size = {}".format(d.size))
print("logic result: {}".format(np.linalg.norm( np.subtract(dC, ldC) ) > 0.1 and d.size > 1))

while np.linalg.norm( np.subtract(dC, ldC) ) > 0.1 and d.size > 1:
    # Re-center
    ldC = dC
    dC, _ = ReCenter(d, dC, killRadius)

df = np.linalg.norm(np.subtract(d, dC), axis=1)

print("df   = {}".format(df))
print("dist = {}".format(dVAfterDivert*SAPs.CV_FINAL_ASSGN_TGO))

ids = np.empty(0, dtype=int)
for i in range(d.shape[0]):
    if df[i] > dVAfterDivert*SAPs.CV_FINAL_ASSGN_TGO:
        ids = np.append(ids, int(i))
    else:
        print("check2 - {}".format(i))
        
print("ids: {}".format(ids))

In [ ]:
kaTraj, trgtTraj = mods.PropagateStatesToDivergence(cvState, aveState, 2.5)
rows = kaTraj.shape[0]
tToInterp = np.arange(kaTraj[rows-4, 6], kaTraj[rows-1, 6], 0.01)

# Interpolate states around coarse resolution POCA
# interpolate with SciPy:
interpKA_SciPy = InterpTraj_SciPy(kaTraj, tToInterp)
interpKA_Brent = InterpTraj_Brent(kaTraj, tToInterp)

interpTrgt_SciPy = InterpTraj_SciPy(trgtTraj, tToInterp)
interpTrgt_Brent = InterpTraj_Brent(trgtTraj, tToInterp)

rndIndxTrgt = np.random.randint(tToInterp.shape[0])
rndIndxKA = np.random.randint(tToInterp.shape[0])
# rndIndxTrgt = 1
# rndIndxKA = 1

print("rKA_SciPy[{}]: {} \nrKA_Brent[{}]: {}".format(rndIndxKA,
    interpKA_SciPy[rndIndxKA, 0:3], rndIndxKA, interpKA_Brent[rndIndxKA,0:3]))
print("rTrgt_SciPy[{}]: {} \nrTrgt_Brent[{}]: {}".format(rndIndxTrgt,
    interpTrgt_SciPy[rndIndxTrgt, 0:3], rndIndxTrgt, interpTrgt_Brent[rndIndxTrgt,0:3]))


In [ ]:
trajTime_Brent = np.zeros((tToInterp.shape[0], kaTraj.shape[1]))
for col in range(kaTraj.shape[1]-1):
    trajTime_Brent[:, col] = pchip(kaTraj[:,6], kaTraj[:,col], tToInterp).transpose()
trajTime_Brent[:, 6] = tToInterp
# use SciPy
trajTime_SciPy = pchip_interpolate(kaTraj[:,6], kaTraj[:, 0:kaTraj.shape[1]], tToInterp, axis=0)

timeColumnDiff = np.subtract(trajTime_SciPy[:,6], trajTime_Brent[:,6])

print("shapes of results - scipy: {}, brent: {}".format(trajTime_SciPy.shape, trajTime_Brent.shape))
print("first row - \nscipy: {} \nbrent: {}".format(trajTime_SciPy[2,:], trajTime_Brent[2,:]))

In [ ]:
iCluster=0
for cluster in clusterList:
    nKVsAssigned = nAssigned[iCluster]
    if nKVsAssigned > 0:
        points = cluster.pts
        print("cluster: {}".format(iCluster))
        print("nKVsAssigned: {}".format(nKVsAssigned))
        print("example of points: {}".format(points))
        nPts = points.shape[0]
        if nKVsAssigned == 1:
            icx = 0
            cents = np.average(points, axis=0)
            print("icx: {}".format(icx))
            print("cents: {}".format(cents))
        else:
            cents, icx = kMeans(points, int( min(nPts, nKVsAssigned)))
            print("icx: {}".format(icx))
            print("cents: {}".format(cents))
    
    iCluster += 1

In [ ]:
tPOCAt, rPOCAt, _ = mods.FindPOCA(cvState, tom[int( np.where(tom[:,8] == tomIds[2])[0] ), 0:7])
cv, _ = mods.GaussProblem(cvState[0:3], rPOCA, tPOCA - cvState[6])
kvFuel = np.ones(SAPs.KV_NUM_KVS) * SAPs.KV_MAX_DIVERT

threatStates = np.empty((tom.shape[0], 7))
for iTomThrt in range(tom.shape[0]):
    threatStates[iTomThrt] = mods.PropagateECI(tom[iTomThrt, 0:7], 0.0, t - tom[iTomThrt, 6])

threatStates = tom[:,0:7]

tomIdsReal = tom[:, 8]
threatIds = tomIds
try:
    ind = int( np.where(tomIds == rvID) ) 
    rvIdTmp = int( threatIDs[ind] )
except TypeError:
    rvIdTmp = 0

# propagate the threats to tPOCA
nThreats = threatStates.shape[0]
threatStatesPOCA = np.zeros(threatStates.shape)
iPOCA = 0
for thrtState in threatStates:
    threatStatesPOCA[iPOCA] = mods.PropagateECI(thrtState, 0.0, tPOCA - thrtState[-1])
    iPOCA += 1

# find the cloud center and separate the positions at POCA for clustering
dVec = threatStatesPOCA[:, 0:3]
center = np.mean( dVec, axis=0 )
centerSave = center.copy()

# perform clustering
tGo = tPOCA - cvState[6]
redThreatStates = threatStates.copy()
delIds = np.empty(0, dtype=int)
clusterList = []
loopCount = 0
while dVec.size > 0:
    cluster = {}
    # find the object furthest from centroid of object map
    print("dVec and center for iteration {}: {}\n{}".format(
        loopCount, dVec.shape, center.shape))
    loopCount += 1
    dCnt, farId, _ = FarPoint(dVec, center)
    # compute the required delta-V for a "virgin" KV to fly there
    tPOCAt, rPOCAt, _ = mods.FindPOCA( cvState,  redThreatStates[farId])
    if mods.vecNorm(cvState[0:3]) == 0 or mods.vecNorm(rPOCAt) == 0:
        print("Trying to use GaussProblem on an origin vector.")
        print("pos1: {}, pos2: {}".format(cvState[0:3], rPOCAt))
        cv = mods.PropagateECI(cvState, 0.0, tPOCA - cvState[6])
    else:
        cv, _ = mods.GaussProblem(cvState[0:3], rPOCAt, tPOCAt - cvState[6])
    print("cv: {} \ncvState: {}".format(cv[3:6], cvState[3:6]))
    # compute the Delta-V required to get there for a KV
#     dV = mods.vecNorm( cv[3:6] - cvState[3:6] )
    dV = np.linalg.norm( cv[3:6] - cvState[3:6] )
    # if the required delta-V is too large, get rid of this threat from the list and start 
    # over. The assumption is that KVs have just been dispensed or are not yet dispensed. 
    # KVs have approximately the same state as the CV, and no fuel has been burned.
    dVAfterDivert = kvFuel[0] - dV - SAPs.KV_FUEL_RESERVE
    tBurn = dV / SAPs.KV_MAX_ACC
    print("dVAfterDivert for iteration {}: {}".format(loopCount-1, dVAfterDivert))
    if dVAfterDivert <= 0:
        print("kvFuel: {}, dV: {}, fuel reserve: {}".format(kvFuel[0], dV, SAPs.KV_FUEL_RESERVE))
    print("tBurn: {} and tGo: {}".format(tBurn,tGo))
    # remove the threats from the threat list that are too far away
    if dVAfterDivert <= 0 or tBurn >= tGo:
        # keep track of which global ids were removed
        delIds = np.append(delIds, threatIds[ farId ])
        print("removed ids: {}".format(delIds))
        # remove non-viable threat from consideration
        redThreatStates = np.delete(redThreatStates, farId, axis=0)
        threatStatesPOCA = np.delete(threatStatesPOCA, farId, axis=0)
        threatIds = np.delete(threatIds, farId, axis=0)
        dVec = np.delete(dVec, farId, axis=0)
        # skip remaining code and re-evaluate loop on the next point
        continue
    # compute the killRadius on the qualified KV
    killRadius = dVAfterDivert * SAPs.CV_FINAL_ASSGN_TGO
    print("killRadius for iteration {}: {}".format(loopCount-1, killRadius))
    # compute the center of all threat objects within 'killRadius' of this object
    # and iterate for a better fit
    dCnt, _ = ReCenter(dVec, dCnt, killRadius)
    diffCtr = np.zeros(3)
#     while mods.vecNorm( dCnt - diffCtr ) > 0.1 and dVec.size > 1:
#         # Re-center
#         diffCtr = dCnt.copy()
#         dCnt, _ = ReCenter(dVec, dCnt, killRadius)
#         print("dCnt from refinind killRadius calculation: {}".format(dCnt))
    # Save as the cluster center location
    cluster.update({"ctr": dCnt})
    # Remove all the objects within 'killRadius' of this object from the object map
    killIds = np.empty(0, dtype=int)
    noKillIds = np.empty(0, dtype=int)
    # calculate distance between each point and the object location
    difference = np.subtract(dVec, dCnt)
    distance = mods.vecNorm(difference, axis=1)
    print("distance array: {}".format(distance))
    indx = 0
    for dist in distance:
        if dist >= killRadius:
            noKillIds = np.append(noKillIds, indx)
        else:
            killIds = np.append(killIds, indx)
        indx += 1
    print("# of objects within killRadius : {}".format(killIds.size))
    print("# of objects outside killRadius: {}".format(noKillIds.size))
    # watch values as loop executes:
    print("ids that are passed back into while loop: {}".format(threatIds))

    # create clusters from the objects corresponding to killIds
    if killIds.size > 0:
        cluster.update({"pts": dVec[ killIds ]})
        cluster.update({"states": threatStatesPOCA[ killIds ]})
        cluster.update({"ids": threatIds[ killIds ]})
        cluster.update({"tPOCA": tPOCA, "kr": killRadius})
        # add current cluster as a SimpleNamespace object to clusterList
        clusterList.append( SimpleNamespace(cluster) )

        # update dVec, threatIds, redThreatStates, threatStatesPOCA 
        # corresponding objects in noKillIds
        dVec = np.delete(dVec, killIds, axis=0)
        redThreatStates = np.delete(redThreatStates, killIds, axis=0)
        threatStatesPOCA = np.delete(threatStatesPOCA, killIds, axis=0)
        threatIds = np.delete(threatIds, killIds, axis=0)
    else:
        break
    
print("\nnumber of computed clusters: {}".format(len(clusterList)))

In [ ]:
pRVs = tom[:, 7]
print("pRVs from MakeTOM: {}, \nassociated ids: {}".format(pRVs, tom[:,8]))

print("rvID: {}".format(rvID))
print("where in tomIds is rvID: {}".format(int( np.where(tomIds == rvID)[0] )))

In [ ]:
pLethalNorm = pLethalGround / np.sum(pLethalGround)

randIds = np.random.permutation(np.arange(pLethalGround.shape[0]-2))[0:pLethalGround.shape[0]-2]

subset = pLethalNorm[randIds]

sumTest = np.sum(pLethalNorm[randIds])

print("pLethalGround: {}, \npLethalNorm: {}".format(pLethalGround, pLethalNorm))
print("randomIds: {}".format(randIds))
print("subsetTest: {}".format(subset))
print("sum of subsetTest: {}".format(sumTest))

In [ ]:
tPOCAt, rPOCAt, _ = FindPOCA(cvState, tom[int( np.where(tom[:,8] == tomIds[2])[0] ), 0:7])
cv, _ = GaussProblem(cvState[0:3], rPOCA, tPOCA - cvState[6])
kvFuel = np.ones(SAPs.KV_NUM_KVS) * SAPs.KV_MAX_DIVERT

threatStates = np.empty((tom.shape[0], 7))
for iTomThrt in range(tom.shape[0]):
    threatStates[iTomThrt] = PropagateECI(tom[iTomThrt, 0:7], 0.0, t - tom[iTomThrt, 6])

threatStates = tom[:,0:7]

tomIdsReal = tom[:, 8]
threatIDs = np.arange(tom.shape[0])
try:
    ind = int( np.where(tomIds == rvID) ) 
    rvIdTmp = int( threatIDs[ind] )
except TypeError:
    rvIdTmp = 0

# propagate the threats to tPOCA
nThreats = threatStates.shape[0]
threatStatesPOCA = np.zeros(threatStates.shape)
for iThrt in range(nThreats):
    threatStatesPOCA[iThrt] = PropagateECI(threatStates[iThrt], 0.0, tPOCA - threatStates[iThrt, 6])

# find the cloud center and separate the positions at POCA for clustering
centerState = np.mean(threatStatesPOCA, axis=0)
center = centerState[0:3]
centerSave = center.copy()
d = threatStatesPOCA[:, 0:3]

# Perform the clustering
x = 1
tGo = tPOCA - cvState[6]
delIDs = np.empty(0, dtype=int)
clusters = []
while d.size > 0:
    cluster = {}
    # find object furthest from the centroid of the object map
    dC, ind, _ = FarPoint(d, center)
    # compute the required delta-V for a "virgin" KV to fly here
    tPOCAt, rPOCAt, _ = FindPOCA(cvState, threatStates[int( threatIDs[ind] )])
    cv, _ = GaussProblem(cvState[0:3], rPOCAt, tPOCAt - cvState[6])
    dV = np.linalg.norm( cv[3:6] - cvState[3:6] ) # Delta-V required to get there for a KV
    # if the required delta-V is too large, get rid of this threat from the list and start 
    # over. The assumption is that KVs have just been dispensed or are not yet dispensed. 
    # KVs have approximately the same state as the CV, and no fuel has been burned.
    dVAfterDivert = kvFuel[0] - dV - SAPs.KV_FUEL_RESERVE
    tBurn = dV / SAPs.KV_MAX_ACC
    if dVAfterDivert <= 0 or tBurn >= tGo:
        # Not enough fuel to reach this threat. Remove if from the list
        delIDs = np.append(delIDs, int( threatIds[ind] ))
        threatIDs = np.delete(threatIDs, ind, 0)
    # d after removing values
    d = np.delete(d, delIDs, 0)

    # compute the kill radius for a KV diverting to this cluster
    killRadius = dVAfterDivert * SAPs.CV_FINAL_ASSGN_TGO
    # compute center of all objects within 'killRadius' of this object
    # and iterate for a better fit.
    dC, _ = ReCenter(d, dC, killRadius)
    ldC = np.zeros(3)
    print("dC shape:  {}".format(dC.shape))
    print("ldC shape: {}".format(ldC.shape))
    while np.linalg.norm( np.subtract(dC, ldC) ) > 0.1 and d.size > 1:
        # Re-center
        ldC = dC
        dC, _ = ReCenter(d, dC, killRadius)
    # save as cluster center location
    cluster.update({"ctr": dC})
    # Remove all objects within 'killRadius' of this object from object map
    tIDOut = np.empty(0, dtype=int)
    idsOut = np.empty(0, dtype=int)
    tIDIn = np.empty(0, dtype=int)
    idsIn = np.empty(0, dtype=int)
    for i in range(d.shape[0]):
        print("loop count: %d" % i)  
        print("d shape: {}".format(d.shape))
        df = np.linalg.norm(d[i] - dC)
        if df >= killRadius:
            tIDOut = np.append(tIDOut, int( i ))
            idsOut = np.append(idsOut, threatIDs[int( i )])
        else:
            tIDIn = np.append(tIDIn, int( i ))
            idsIn = np.append(idsIn, threatIDs[int( i )])

    print("tIDOut: {}, \ntIDIn: {}".format(tIDOut,tIDIn))
    print("tIDOut shape: {}, tIDIn shape: {}, d shape: {}".format(tIDOut.shape, tIDIn.shape, d.shape))
    print("idsOut: {}, idsIn: {}".format(idsOut,idsIn))
    print("idsOut shape: {}, idsIn shape: {}".format(idsOut.shape, idsIn.shape))

    d = d[tIDOut]
    print("d: {}".format(d))
    threatIDs = idsOut
    if d.size > 0:
        statesIn = threatStatesPOCA[idsIn]
        # add values to the cluster dictionary
        cluster.update({"pts": d[tIDIn], "states": statesIn, "ids": idsIn}) 
        cluster.update({"tPOCA": tPOCA, "kr": killRadius})
        clusters.append(SimpleNamespace(cluster))
        #clusters.append(cluster)
        
    d = np.delete(d, tIDIn, 0)
    threatIDs = tIDOut
    
#     if d.size > 0:
# tIDOut: [1 2 3 4 5], 
# tIDIn: [0]
# tIDOut shape: (5,), tIDIn shape: (1,), d shape: (5, 3)
#         statesIn = threatStatesPOCA[tIDIn]
#         # add values to the cluster dictionary
#         cluster.update({"pts": d[tIDIn], "states": statesIn, "ids": tIDIn, "tPOCA": tPOCA, "kr": killRadius})
#         #clusters.append(SimpleNamespace(cluster))
#         clusters.append(cluster)
